version: '3'
services:
  frontend:
    build: frontend/
    restart: on-failure
    ports: 
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./logs:/var/log/frontend
    networks:
      - virtual-network-1
  backend:
    build: backend/
    restart: on-failure
    ports:
      - 3001:3001
    environment:
      - DB_HOST=database
    depends_on:
      - database
    networks:
      - virtual-network-1
      - virtual-network-2
  database:
    image: betrybe/docker-compose-example-database:v1
    restart: on-failure
    volumes:
      - banco-de-dados:/data/db
    networks:
      - virtual-network-2

volumes:
  banco-de-dados:

networks:
  virtual-network-1:
  virtual-network-2:
